- name: 'Deploy site'
  hosts: webserver
  gather_facts: false

  tasks:
    - name: 'checkout master'
      git:
        repo: 'git@github.com:turbokuzmich/stopvirus.git'
        dest: '{{ site_path }}'
        version: 'master'
    - name: 'install dependencies'
      shell:
        cmd: 'npm ci'
        chdir: '{{ site_path }}'
    - name: 'build site'
      shell:
        cmd: 'npm run build'
        chdir: '{{ site_path }}'
