- name: 'Deploy site'
  hosts: webserver
  gather_facts: false

  tasks:
    - name: 'checkout'
      git:
        repo: 'git@github.com:turbokuzmich/stopvirus.git'
        dest: '{{ site_path }}'
        version: 'master'
    - name: 'dependencies'
      shell:
        cmd: 'npm ci'
        chdir: '{{ site_path }}'
    - name: 'build'
      shell:
        cmd: 'npm run build'
        chdir: '{{ site_path }}'
    - name: 'restart'
      shell:
        cmd: 'pm2 restart {{ pm2_config }}'
